---
- name: "{{ nginx_setup | capitalize }} NGINX"
  when: nginx_enable | bool
  tags: nginx_enable
  block:
    - name: "{{ nginx_setup | capitalize }} NGINX Open Source"
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/opensource/install-oss.yml"
      when: nginx_type == 'opensource'
      tags: nginx_install_oss




